name: build/test/deploy
on:
  push:
    branches:
      - master
      - "release/**"
jobs:
  buildAndTest:
    name: build and test
    runs-on: macos-latest
    strategy:
      matrix:
        project: ["SuperSmashBrosStats.xcodeproj"]
        scheme: ["SuperSmashBrosStats"]
        destination:
          [
            "platform=iOS Simulator,OS=13.4.1,name=iPad Pro (12.9-inch) (4th generation)",
            "platform=iOS Simulator,OS=13.4.1,name=iPhone 11 Pro Max",
          ]
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        run: |
          xcodebuild test -project "${project}" -scheme "${scheme}" -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
          scheme: ${{ matrix.scheme }}
          project: ${{ matrix.project }}
